[package]
name = "drpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
dirs = "5.0.1"
discord-rpc-client = "0.4.0"
fork = "0.1.23"
interprocess = "1.2.1"
rspotify = "0.12.0"
serde = "1.0.197"
tokio = { version = "1.36.0", features = ["full"] }
toml = "0.8.10"
